### ISSUE TITLE
`GuiColorPicker()` color slider stuck

### ISSUE THREAD

**Issue by 0r33** [raysan5/raygui#92] opened 2020-06-13 05:41 UTC
If you drag the little dot on the color gradient square all the way to the left hand side of the square then the vertical color slider on the right moves to and gets stuck on red.
You can also test this by setting colorPickerValue to BLACK in the controls_test_suite example. Then you can't move the color slider.
The vertical color bar also moves slightly when moving the dot around.
Tested on the latest raygui and raylib 3.0

**Comment by raysan5** [comment] 2020-06-19 11:27
@sh4mbler thanks for reporting! good catch!

All those issues are probably related to color rounding, that funtion performs internally several color conversion from float to unsigned char...

**Comment by TSnake41** [comment] 2021-09-10 22:41
The problem is mostly due to these details : 
 - `BLACK` color has no concept of hue nor saturation, which means that any value of H or S with V = 0 is black, so in the case of raylib is H and S are 0 by default, which explains why the slider gets stuck to red (H = 0)
 - some roundings makes raw mouse input -> color -> final square coordinates differents

It can be solved, but the API will need to be modified to store the coordinates of the square (and therefore be stateful in some way, which is non-goal on raygui)

**Comment by raysan5** [comment] 2021-10-05 09:37
@TSnake41 I'm afraid storing the values would break the immediate-mode nature of the library. Also note that separate data would need to be registered for every `GuiColorPicker()` used (in case several ones are used). I'm closing this issue for now.

I still think it can, maybe, reviewed in a way (maybe with some roundings/normalizations?) to avoid the issue with no extra variables. I leave that investigation work for future adventures.

**Closed by raysan5** 2021-10-05 09:37 UTC
