### ISSUE TITLE
Custom File Dialog example C and h errors

### ISSUE THREAD

**Issue by Axle-Ozz-i-sofT** [raysan5/raygui#235] opened 2022-10-25 04:22 UTC
Hi,
I have attempted to compile custom_file_dialog.c with gui_file_dialog.h [raygui v3.2](https://github.com/raysan5/raygui/releases/tag/3.2) #define GUI_FILE_DIALOG_IMPLEMENTATION with multiple "gui_file_dialog.h	[Error] conflicting types for 'LoadDirectoryFiles', gui_file_dialog.h [Error] too few arguments to function 'LoadDirectoryFiles' etc

I copied the the current files from https://github.com/raysan5/raygui/tree/master/examples/custom_file_dialog (I cant give a version, Realease 3.2 and the current are both stamped FileDialog v1.1)
Compiled with #define GUI_FILE_DIALOG_IMPLEMENTATION **except I am not getting file list to select**.
![CustomFileDialog](https://user-images.githubusercontent.com/57524738/197680439-96084da0-8373-4205-a7b9-7cabb6e12988.png)

I tried also to compile with #define USE_CUSTOM_LISTVIEW_FILEINFO but get "Incompatible Types" error.

230	77	W:\__Dev_Projects_Active\RaylibTests\C\gui_file_dialog.h	[Error] incompatible types when assigning to type 'FileInfo' {aka 'struct FileInfo'} from type 'char *'

291	146	W:\__Dev_Projects_Active\RaylibTests\C\gui_file_dialog.h	[Error] incompatible type for argument 2 of 'GuiListViewFiles'

375	37	W:\__Dev_Projects_Active\RaylibTests\C\gui_file_dialog.h	[Error] incompatible type for argument 1 of 'free'

So appears to be something wrong with the way the the memory(type) is being allocated to typedef struct FileInfo { ... }
dirFilesIcon[i] = **(char *)**RL_CALLOC(MAX_DIR_PATH_LENGTH, 1)

I don't understand enough on the internals of raylib/gui atm to correct this myself :(

Axle

**Comment by raysan5** [comment] 2022-10-25 09:12
This issue is a duplicate of #224

**Comment by Axle-Ozz-i-sofT** [comment] 2022-10-26 00:06
Well not really, that thread seamed focused upon the C++ solutions. So I was attempting to keep the C solution separate.
I will continue with  #224 from now if preferred.
Axle

**Closed** 2022-11-07 10:21 UTC
